---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: kafka-operator
      sourceRef:
        kind: HelmRepository
        name: kubernetes-charts.banzaicloud.com-mirror
        namespace: ${workspaceNamespace}
      version: 0.20.2
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: kafka-operator
  valuesFrom:
    - kind: ConfigMap
      name: kafka-operator-0.20.2-d2iq-defaults
  targetNamespace: ${releaseNamespace}
