---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-operator-0.2.15-dkp.1-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    hooks:
      image:
        repository: bitnami/kubectl
        tag: 1.27.6
