---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-operator-0.2.14-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    # We forked the zookeeper-operator in order to support k8s 1.25+.
    # Once https://github.com/pravega/zookeeper-operator/commit/adcf3bf0adaf1aef2c3f0fb89aff8c5bde1e0021
    # is released, we can move back to the upstream operator image.
    image:
      repository: mesosphere/zookeeper-operator
      tag: 0.2.14-d2iq
