version: 2
updates:
  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/tests"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
