---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-operator-0.2.15-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    hooks:
      image:
        repository: lachlanevenson/k8s-kubectl
        tag: v1.25.4
