# Kubernetes versions
# (e.g. 1.23.0 - has to match versions in https://github.com/yannh/kubernetes-json-schema)
k8s_versions:
  - 1.23.6
  - 1.24.6
  - 1.25.4
  - 1.26.6

# paths to load (in that order)
paths:
  - helm-repositories
  - services

# use strict validation (reject unknown fields in resources)
strict: true

# types to be skipped (e.g. certmanager.k8s.io/v1, or certmanager.k8s.io/v1/Certificate)
skip_types: []

# load additional CRDs (URLs of CRD yaml files)
additional_crds:
  # Flux types are installed by Kommander, not included in this repository
  - https://github.com/fluxcd/source-controller/releases/download/v0.24.4/source-controller.crds.yaml

# set values for substitution variables (e.g. ${releaseNamespace}) in the resources
substitution_vars:
  releaseNamespace: kommander
  workspaceNamespace: workspace
