# Kubernetes versions
# (e.g. 1.23.0 - has to match versions in https://github.com/yannh/kubernetes-json-schema)
k8s_versions:
  - 1.28.7
  - 1.29.9
  - 1.30.5
  - 1.31.1

# paths to load (in that order)
paths:
  - helm-repositories
  - services

# use strict validation (reject unknown fields in resources)
strict: true

# types to be skipped (e.g. certmanager.k8s.io/v1, or certmanager.k8s.io/v1/Certificate)
skip_types: []

# load additional CRDs (URLs of CRD yaml files)
additional_crds:
  # Flux types are installed by Kommander, not included in this repository
  - https://github.com/fluxcd/source-controller/releases/download/v1.3.0/source-controller.crds.yaml
  - https://github.com/fluxcd/helm-controller/releases/download/v1.0.1/helm-controller.crds.yaml

# set values for substitution variables (e.g. ${releaseNamespace}) in the resources
substitution_vars:
  releaseNamespace: kommander
  workspaceNamespace: workspace
