ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}

RUN apt-get update && apt-get install -y \
    curl \
    bzip2 \
    git \
    build-essential \
    python-dev \
    python3 \
    python3-pip \
    shellcheck \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pre-commit yamale yamllint awscli gitlint

ARG ASDF_VERSION
RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v${ASDF_VERSION}
RUN echo ". ${HOME}/.asdf/asdf.sh" >> ${HOME}/.bashrc

ARG DOCKER_VERSION
RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz | \
    tar xz -C /usr/local/bin --strip-components=1 docker/docker

ARG GH_VERSION
RUN curl -Lf https://github.com/cli/cli/releases/download/v${GH_VERSION}/gh_${GH_VERSION}_linux_amd64.tar.gz | tar -xz -C /usr/local/bin/ --strip-components 2 gh_${GH_VERSION}_linux_amd64/bin/gh

RUN --mount=type=bind,target=/tmp/dkp-catalog-applications,readwrite=true \
    cd /tmp/dkp-catalog-applications && \
    bash -ec ". ~/.asdf/asdf.sh && make install-tools" && \
    pre-commit install -t pre-commit -t commit-msg --install-hooks

RUN mkdir -p ~/.ssh && echo 'github.com,140.82.118.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' > ~/.ssh/known_hosts
