---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-operator-0.20.2-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    certManager:
      enabled: true
    crd:
      enabled: true
