---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubernetes-charts.banzaicloud.com
  namespace: ${workspaceNamespace}
spec:
  url: https://kubernetes-charts.banzaicloud.com
  interval: 10m
