---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: spark-operator
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-spark-charts
      version: 1.1.6
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: spark-operator
  valuesFrom:
    - kind: ConfigMap
      name: spark-operator-1.1.6-d2iq-defaults
  targetNamespace: ${releaseNamespace}
