---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubernetes-charts.banzaicloud.com-mirror
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: supported
spec:
  url: "${helmMirrorURL:=https://mesosphere.github.io/charts/staging}"
  interval: 10m
