---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zookeeper-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: zookeeper-operator
      sourceRef:
        kind: HelmRepository
        name: charts.pravega.io
        namespace: ${workspaceNamespace}
      version: 0.2.15
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: zookeeper-operator
  valuesFrom:
    - kind: ConfigMap
      name: zookeeper-operator-0.2.17-d2iq-defaults
  targetNamespace: ${releaseNamespace}
