---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-operator-0.25.2-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    certManager:
      enabled: true
    crd:
      enabled: true
    prometheusMetrics:
      authProxy:
        image:
          repository: gcr.io/kubebuilder/kube-rbac-proxy
          tag: v0.14.1
