---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mesosphere.github.io-spark-charts
  namespace: ${workspaceNamespace}
spec:
  url: "${helmMirrorURL:=http://mesosphere.github.io/spark-on-k8s-operator}"
  interval: 10m
