---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: charts.pravega.io
  namespace: ${workspaceNamespace}
spec:
  url: "${helmMirrorURL:=https://charts.pravega.io}"
  interval: 10m
