name: cve-reporter-scan
on:
#   push:
#     branches:
#       - 'main'
#     tags:
#       - 'v*'
  workflow_dispatch:

env:
  GITHUB_TOKEN: "${{ secrets.MESOSPHERECI_USER_TOKEN }}"
  CVE_REPORTER_API_KEY: "${{ secrets.CVE_REPORTER_API_KEY }}"

jobs:
  cve_scan:
    runs-on:
      - self-hosted
      - small
    steps:
      - name: Checks out the dkp-catalog-applications repository at the exact ref that triggered the workflow
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push images to CVE reporter
        run:  make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make cve-reporter.push-images CVE_REPORTER_PROJECT_VERSION='${{ github.ref_name }}'"
