name: cve-reporter-dcos-export

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: |
          Choose an action. POST creates a doc project version selector in CVE reporter. DELETE
           on the other hand, removes the doc project version selector in CVE reporter.
        required: true
        options:
          - 'POST'
          - 'DELETE'
      project-version:
        description: "The DKP Applications Catalog version"
        required: true
        type: string

env:
  CVE_REPORTER_API_KEY: "${{ secrets.CVE_REPORTER_API_KEY }}"
  PROJECT_NAME: "dkp-catalog-applications"

jobs:
  docs-export:
    runs-on:
      - self-hosted
      - small
    steps:
      - name: Submit request to the CVE reporter
        id: request
        uses: mesosphere/workflow-db/actions/cve-reporter/docs-export@main
        with:
          bearer_token: $CVE_REPORTER_API_KEY
          http-method: ${{ inputs.action}}
          project-name: $PROJECT_NAME
          project-version: ${{ inputs.project-version}}
      - name: API Result
        run: |
          echo "Response code: ${{ steps.request.outputs.response_code }}"
          echo "Response Body: ${{ steps.request.outputs.response_body }}"
