name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install pre-commit
        run: pip install --upgrade pre-commit gitlint

      - name: Install shell-check
        run: apt update && apt install -y shellcheck

      - name: make pre-commit
        run: make pre-commit
